#!/bin/bash
echo 'cpu:' $(grep 'cpu ' /proc/stat \
    | awk '{usage=($2+$4)*100/($2+$4+$5)} END {printf "%.1f%s",usage,"%"}')
echo "mem:" $(awk '
        BEGIN { total=0; free=0 }
        /MemTotal:/ { total=$2; }
        /MemFree:/ { free+=$2; }
        /Buffers:/ { free+=$2; }
        /Cached:/ { free+=$2; }
        /MemAvailable:/ { free=$2; exit; }
        END { printf "%.2fGB / %.2fGB",(total-free)/1000000,total/1000000 }
    ' /proc/meminfo)
